#####################################################################################
#                                                                                   #
#    #          ####     ####    #    #   #          ####     ####    #   #    #    #
#    #         #    #   #    #   #   #    #         #    #   #    #   #   ##   #    #
#    #         #    #   #        ####     #         #    #   #        #   # #  #    #
#    #         #    #   #        #  #     #         #    #   #  ###   #   #  # #    #
#    #         #    #   #    #   #   #    #         #    #   #    #   #   #   ##    #
#    #######    ####     ####    #    #   #######    ####     ####    #   #    #    #
#                                                                                   #
#####################################################################################
name: LockLogin
version: ${project.version}
author: ${project.author}
description: ${project.description}
website: ${project.url}
main: eu.locklogin.plugin.bukkit.Main
database: false
api-version: 1.13
load: STARTUP
depend:
  - AnotherBarelyCodedKarmaPlugin

#ProtocolLib soft dependency is for modules
#that require that plugin ( LockLoginPremium
#as example )
softdepend:
  - AnotherBarelyCodedKarmaPlugin
  - PlaceholderAPI
  - ProtocolLib



#####################################################################################################
#                                                                                                   #
#      ######     #######     ##     ##   ##     ##      ###      ##    ##   ########     ######    #
#    ##     ##   ##     ##    ###   ###   ###   ###     ## ##     ###   ##   ##     ##   ##    ##   #
#    ##          ##     ##    #### ####   #### ####    ##   ##    ####  ##   ##     ##   ##         #
#    ##          ##     ##    ## ### ##   ## ### ##   ##     ##   ## ## ##   ##     ##    ######    #
#    ##          ##     ##    ##     ##   ##     ##   #########   ##  ####   ##     ##         ##   #
#    ##     ##   ##     ##    ##     ##   ##     ##   ##     ##   ##   ###   ##     ##   ##    ##   #
#      ######     #######     ##     ##   ##     ##   ##     ##   ##    ##   ########     ######    #
#                                                                                                   #
#####################################################################################################
commands:
  locklogin:
    description: The command to manage the plugin, such as reload, or apply updates
  slocklogin:
    description: Spigot version of the locklogin command for bungeecord mode
  setloginspawn:
    description: The command to set login spawn, must be enabled in config.yml!
  register:
    description: The command that allows a player to register
    aliases:
      - reg
  login:
    description: The command that allows a player to login into his account
    aliases:
      - log
  panic:
    description: The command that allows a player to authenticate his panic token
  pin:
    description: The command that allows a player to manage his pin
  2fa:
    description: The command that allows a player to manage his 2FA settings
  playerinfo:
    description: The command that allows a player to view a player information
  alias:
    description: The command that allows a player to create/manage aliases of playerinfo
  account:
    description: The command that allows a player to manage account
  lastloc:
    description: The command that allows a player to manage last locations



#################################################################
#                                                               #
#    ########    ########   ########    ##     ##    ######     #
#    ##     ##   ##         ##     ##   ###   ###   ##    ##    #
#    ##     ##   ##         ##     ##   #### ####   ##          #
#    ########    ######     ########    ## ### ##    ######     #
#    ##          ##         ##   ##     ##     ##         ##    #
#    ##          ##         ##    ##    ##     ##   ##    ##    #
#    ##          ########   ##     ##   ##     ##    ######     #
#                                                               #
#################################################################
permissions:
  locklogin.reload:
    children:
      locklogin.reload.config:
        description: The permission required to reload only configuration file
        default: false
      locklogin.reload.messages:
        description: The permission required to reload only messages file
        default: false
    description: The permission required to reload configuration/messages files
    default: false
  locklogin.location:
    children:
      locklogin.location.spawn:
        description: The permission required to set spawn
        default: false
      locklogin.location.client:
        description: The permission required to manage client last location
        default: false
    description: The permission required to manage locations
    default: false
  locklogin.info:
    children:
      locklogin.info.request:
        description: The permission required to request information about a player account
        default: op
      locklogin.info.alt:
        children:
          locklogin.info.alt.alert:
            description: The permission required to be notified when LockLogin detects there may be a player using alt account
            default: false
        description: The permission required to request a list of possible alt accounts
        default: op
    description: The permission required to view clients information
    default: false
  locklogin.account:
    children:
      locklogin.account.close:
        description: The permission required to close a client session
        default: false
      locklogin.account.remove:
        description: The permission required to remove a client account
        default: false
      locklogin.account.unlock:
        description: The permission required to unlock a client account after being removed
        default: false
    description: The permission required to manage player accounts
    default: false
  locklogin.forcefa:
    description: The permission required to force clients to use 2fa
    default: false
  locklogin.alias:
    description: The permission required to use /alias command
    default: false
  locklogin.module:
    children:
      locklogin.module.reload:
        description: The permission required to reload a module
        default: false
      locklogin.module.load:
        description: The permission required to load modules
        default: false
      locklogin.module.unload:
        description: The permission required to unload a module
        default: false
      locklogin.module.list:
        description: The permission required to list modules
        default: false
    description: The permission required to manage modules
    default: false
  locklogin.updater:
    children:
      locklogin.updater.apply:
        description: The permission required to apply updates
        default: false
      locklogin.updater.version:
        description: The permission required to view current and latest version
        default: op
      locklogin.updater.changelog:
        description: The permission required to fetch changelog
        default: op
      locklogin.updater.check:
        description: The permission required to check for updates
        default: false
    description: The permission required to manage plugin updater
    default: false
  locklogin.web:
    children:
      locklogin.web.log:
        description: The permission required to upload logs to the web
        default: false
      locklogin.web.sync:
        description: The permission required to synchronize web data
        default: false
      locklogin.web.remove:
        description: The permission required to remove queries in web data
        default: false
      locklogin.web.execute:
        description: The permission required to execute queries in web data
        default: false
    description: The permission required for web related options in LockLogin
    default: false